name: Build ImmortalWrt ARM64 Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 固定官方版本（保证永远不报错、永远有版本号）
      - name: 设置官方版本号
        run: |
          echo "IW_VERSION=24.10.5" >> $GITHUB_ENV

      # 下载固件
      - name: 下载官方 rootfs
        run: |
          wget -O rootfs.tar.gz https://immortalwrt.org/releases/${IW_VERSION}/targets/armvirt/64/rootfs.tar.gz

      # 登录GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建并推送（两个标签：latest + 官方版本号）
      - name: 构建并推送
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/seaking111/immortalwrt-arm64:latest
            ghcr.io/seaking111/immortalwrt-arm64:${{ env.IW_VERSION }}
